### ISSUE TITLE
[Question] Multiply is good for tta?

### ISSUE THREAD

**Issue by piantic** [kentaroy47/ODA-Object-Detection-ttA#10]
Hi, I saw Multiply in oda.py.

```
class Multiply(Base):
    # change brightness of image
    def __init__(self, scale):
        # scale is a float value 0.5~1.5
        self.scale = scale
    def augment(self, image):
        return image*self.scale    
    def batch_augment(self, images):
        return images*self.scale    
    def deaugment_boxes(self, boxes):
        return boxes
```

I didn't even think about this type of TTA, but I'm curious if it works.
p.s. At first I saw, brightness in code comment and class name did not match well.

**Comment by kentaroy47** [comment]
I implemented Multiply because it was used in ttach.
The TTA itself was not effective in Kaggle GWD, but may be effective if image brightness greatly differs within the image :)

**Comment by piantic** [comment]
Thanks for replying. :)
