### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by gauravgund** [kentaroy47/ODA-Object-Detection-ttA#13]
I am trying to call tta_model to return boxes, confidences and labels using 'boxes, scores, labels = tta_model(img)'.

But I am getting the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-29-587b6d8d382c> in <module>()
----> 1 boxes, scores, labels = tta_model(img)

4 frames
/usr/local/lib/python3.7/dist-packages/odach/oda.py in __call__(self, img)
    218             # gen img
    219             inf_img = tta.batch_augment(img.clone())
--> 220             results = self.model_inference(inf_img)
    221             # iter for batch
    222             for result in results:

/usr/local/lib/python3.7/dist-packages/odach/oda.py in model_inference(self, img)
    205     def model_inference(self, img):
    206         with torch.no_grad():
--> 207             results = self.model(img)
    208         return results
    209 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/content/pytorch-YOLOv4/tool/darknet2pytorch.py in forward(self, x)
    224             return out_boxes
    225         else:
--> 226             return get_region_boxes(out_boxes)
    227 
    228     def print_network(self):

/content/pytorch-YOLOv4/tool/torch_utils.py in get_region_boxes(boxes_and_confs)
     55     for item in boxes_and_confs:
     56         boxes_list.append(item[0])
---> 57         confs_list.append(item[1])
     58 
     59     # boxes: [batch, num1 + num2 + num3, 1, 4]

IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by kentaroy47** [comment]
solved by #16
