### ISSUE TITLE
Error when image contains no bounding box

### ISSUE THREAD

**Issue by sahilg06** [kentaroy47/ODA-Object-Detection-ttA#15]
### Case 1 (batch size =1)
when I pass a single image(1,3,1024,1024) to tta_model, it gives the following error 
```
 File "FRCNN_Resnet_inference.py", line 83, in <module>
    boxes, scores, labels = tta_model(image) #implementing tta
  File "/opt/conda/lib/python3.8/site-packages/odach/oda.py", line 226, in __call__
    if np.max(box)>1:
  File "<__array_function__ internals>", line 5, in amax
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2733, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```
I think in the code it is written  `np.max(box)>1` to normalize . If the image contains no bbox, then **box** variable will be empty and hence the above error, I think we can add an additional condition of `box.size != 0` or can do this `np.max(box, initial=1)>1`

### Case 2 (batch size>1)
When I pass the input of size **[8,3,1024,1024]** (say batch_size=8), I get the output as boxes of size (433, 4). Sow how will I know, which boxes correspond to which image in the batch?

**Comment by sahilg06** [comment]
Another doubt: Shouldn't we divide box by **img.shape-1** instead of **img.shape** to normalize in the below code?

<img width="665" alt="Screenshot 2021-06-30 at 22 25 13" src="https://user-images.githubusercontent.com/59660566/124001300-1aceb700-d9f2-11eb-8f49-6eb554181096.png">

**Comment by kentaroy47** [comment]
>Another doubt: Shouldn't we divide box by img.shape-1 instead of img.shape to normalize in the below code?

That's true. I will fix this.
